### PR TITLE
[Android] Change recommended code snippets

### PR DESCRIPTION
**Pull request by arifBurakDemiray**

### CODE REVIEW

**Review by AliRKat — COMMENTED** [review]
Very cool work! 🚀 

I have some suggestions, but I would love to talk about them. 
1- Do we have a general naming convention for star rating? I think the best way to write, and what Grammarly usually suggests, is a Star-Rating. There are instances of both "Star rating" and "Star Rating" I believe the way I suggest helps for readability. 
2- In the optional section, there is an option for "Disable Asking Star rating completely" when I click that I would like to see next option to fade out or sth, meaning that clicking over that is not necessary etc. 
3- Do we go with "salt" or was it sth like "Parameter Tampering Salt" 
4- I think we should treat all of the texts on buttons like headers. f.e. in the bottom I think it should be "Generate Code" or just "Generate"

**Comment by turtledreams** [comment]
> Very cool work! 🚀
> 
> I have some suggestions, but I would love to talk about them. 1- Do we have a general naming convention for star rating? I think the best way to write, and what Grammarly usually suggests, is a Star-Rating. There are instances of both "Star rating" and "Star Rating" I believe the way I suggest helps for readability. 2- In the optional section, there is an option for "Disable Asking Star rating completely" when I click that I would like to see next option to fade out or sth, meaning that clicking over that is not necessary etc. 3- Do we go with "salt" or was it sth like "Parameter Tampering Salt" 4- I think we should treat all of the texts on buttons like headers. f.e. in the bottom I think it should be "Generate Code" or just "Generate"

all seems valid

**Review by turtledreams — CHANGES_REQUESTED** [review]
I run it and it looks nice, but you should add to changelog what you changed

**Comment by arifBurakDemiray** [comment]
oww it have changelog, on it

**Review by turtledreams — APPROVED** [review]

**Pull request merged**
